version: "3.8"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: notesadmin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notesapi
    ports:
      - '5432:5432'
    volumes:
      - ./scripts/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - db:/var/lib/postgresql/data

  notes-app:
    build:
      context: ./server
    depends_on:
      - postgres
    ports:
      - '4000:4000'
    environment:
      DB_HOST: postgres
      PORT: 4000
    volumes:
      - ./notes:/opt/notes


volumes:
  db:
